

import GeekyGadgets.Semantics.Markups.Globals as _Globals

class SVG(_Globals.HasCSS, _Globals.Markup):
	_explicitAttributeNames = ["preserveAspectRatio", "viewBox", "markerWidth", "markerHeight", "refX", "refY"]

class Svg(SVG): ...

class A(SVG): ...
class Animate(SVG): ...
class AnimateMotion(SVG): ...
class AnimateTransform(SVG): ...
class Circle(SVG): ...
class ClipPath(SVG): ...
class Defs(SVG): ...
class Desc(SVG): ...
class Ellipse(SVG): ...
class FeBlend(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeColorMatrix(SVG): ...
class FeComponentTransfer(SVG): ...
class FeComposite(SVG): ...
class FeConvolveMatrix(SVG): ...
class FeDiffuseLighting(SVG): ...
class FeDisplacementMap(SVG): ...
class FeDistantLight(SVG): ...
class FeSpecularLighting(SVG): ...
class FeDropShadow(SVG): ...
class FeFlood(SVG): ...
class FeFuncA(SVG): ...
class FeFuncB(SVG): ...
class FeFuncG(SVG): ...
class FeFuncR(SVG): ...
class FeGaussianBlur(SVG): ...
class FeImage(SVG): ...
class FeMerge(SVG): ...
class FeMergeNode(SVG): ...
class FeMorphology(SVG): ...
class FeOffset(SVG): ...
class FePointLight(SVG): ...
class FeSpotLight(SVG): ...
class FeTile(SVG): ...
class FeTurbulence(SVG): ...
class Filter(SVG): ...
class ForeignObject(SVG): ...
class G(SVG): ...
class Image(SVG): ...
class Line(SVG): ...
class LinearGradient(SVG): ...
class Marker(SVG): ...
class Path(SVG): ...
class Polyline(SVG): ...
class Polygon(SVG): ...
class Mask(SVG): ...
class Metadata(SVG): ...
class Mpath(SVG): ...
class Pattern(SVG): ...
class RadialGradient(SVG): ...
class Rect(SVG): ...
class Script(SVG): ...
class Set(SVG): ...
class Stop(SVG): ...
class Style(SVG): ...
class Switch(SVG): ...
class Symbol(SVG): ...
class Use(SVG): ...
class Text(SVG):
	_explicitAttributeNames = ["textLength", "lengthAdjust"]
class TextPath(SVG): ...
class Title(SVG): ...
class Tspan(SVG): ...
class View(SVG): ...



del _Globals