

from GeekyGadgets.Semantics.Markup import Globals as _Globals
from GeekyGadgets.Formatting.Case import CamelCase as _CamelCase

class SVG(_Globals.DeclaredTag):
	def __init_subclass__(cls, name=None, **kwargs) -> _Globals.NoneType:
		return super().__init_subclass__(name=name or _CamelCase(cls.__name__), **kwargs)

class A(SVG): ...
class Animate(SVG): ...
class AnimateMotion(SVG): ...
class AnimateTransform(SVG): ...
class Circle(SVG): ...
class ClipPath(SVG): ...
class Defs(SVG): ...
class Desc(SVG): ...
class Ellipse(SVG): ...
class FeBlend(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeColorMatrix(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeComponentTransfer(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeComposite(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeConvolveMatrix(SVG): ...
class FeDiffuseLighting(SVG): ...
class FeDisplacementMap(SVG): ...
class FeDistantLight(SVG): ...
class FeDiffuseLighting(SVG): ...
class FeSpecularLighting(SVG): ...
class FeDropShadow(SVG): ...
class FeFlood(SVG): ...
class FeFuncA(SVG): ...
class FeFuncB(SVG): ...
class FeFuncG(SVG): ...
class FeFuncR(SVG): ...
class FeGaussianBlur(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeImage(SVG): ...
class FeMerge(SVG): ...
class FeMergeNode(SVG): ...
class FeMerge(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeMorphology(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeOffset(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FePointLight(SVG): ...
class FeSpecularLighting(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeSpotLight(SVG): ...
class FeTile(SVG): ...
class FilterPrimitiveReference(SVG): ...
class FeTurbulence(SVG): ...
class Filter(SVG): ...
class ForeignObject(SVG): ...
class G(SVG): ...
class Image(SVG): ...
class Line(SVG): ...
class LinearGradient(SVG): ...
class Marker(SVG): ...
class Path(SVG): ...
class Line(SVG): ...
class Polyline(SVG): ...
class Polygon(SVG): ...
class Mask(SVG): ...
class Metadata(SVG): ...
class Mpath(SVG): ...
class AnimateMotion(SVG): ...
class Path(SVG): ...
class Path(SVG): ...
class Pattern(SVG): ...
class Polygon(SVG): ...
class Polyline(SVG): ...
class RadialGradient(SVG): ...
class Rect(SVG): ...
class Script(SVG): ...
class Script(SVG): ...
class Set(SVG): ...
class Stop(SVG): ...
class Style(SVG): ...
class Svg(SVG): ...
class Switch(SVG): ...
class Symbol(SVG): ...
class Use(SVG): ...
class Text(SVG): ...
class TextPath(SVG): ...
class Title(SVG): ...
class Tspan(SVG): ...
class Text(SVG): ...
class Use(SVG): ...
class View(SVG): ...
